apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: oci-vault-db-password
spec:
  provider: oci
  parameters:
    vaultId: {{ .Values.vaultOCID }}
    secrets: |
      - secretName: my-db-password
        secretOCID: {{ .Values.secretOCID }}