apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}
  labels:
    app: {{ .Values.app }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.servicePort | default 80 }}
      targetPort: {{ .Values.port }}
