name: Feature Branch CI

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  push:
    branches:
      - 'feature/*'
    paths-ignore:
      - 'deploy/**'
      - '**/*.md'
      - 'versions.json'
      - 'doc/**'
    tags-ignore:
      - '**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  call-ci:
    name: Feature-CI Workflow
    uses: mdefenders/shared-workflows/.github/workflows/feature-ci.yaml@dev
    secrets: inherit