name: Feature Branch CI

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  push:
    branches:
      - 'feature/*'
    paths-ignore:
      - 'deploy/**'
      - '**/*.md'
      - 'versions.json'
      - 'doc/**'
    tags-ignore:
      - '**'
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: false

jobs:
  call-ci:
    name: Feature-CI Workflow
    uses: mdefenders/shared-workflows/.github/workflows/dev-ci.yaml@dev
    with:
      deploy-to-environment: 'dev'
    secrets: inherit