name: Staging  CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'deploy/**'
      - '**/*.md'
      - 'versions.json'
      - 'doc/**'
    tags-ignore:
      - '**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  call-ci:
    name: Staging-CI Workflow
    uses: mdefenders/shared-workflows/.github/workflows/dev-ci.yaml@dev
    with:
      deploy-to-environment: 'staging'
    secrets: inherit